// Copyright Miroslav Valach

#pragma once

#include "CoreMinimal.h"
//ToDo is this required by anything at all ?
//#include "UObject/NoExportTypes.h"
#include "UDActionData.h"
#include "UDWorldState.generated.h"

/**
 * Represents single tile.
 * This needs to be duplicated as it's not generated by pure actions.
 */
UCLASS()
class UNREALDIPLOMACY_API UUDTileState : public UObject
{
	GENERATED_BODY()
public:
	/**
	 * Creates new instance of the tile state for specific location in array.
	 */
	static TObjectPtr<UUDTileState> CreateState(int32 x, int32 y);
	/**
	 * Creates new instance of the tile state for specific location in array.
	 */
	static TObjectPtr<UUDTileState>&& Duplicate(TObjectPtr<UUDTileState> existingState);
	/**
	 * Position in map array.
	 */
	FIntPoint Position;
	/**
	 * Owner's unique id.
	 * Default is UUDWorldState::GaiaWorldStateId as this is inherently part of world state.
	 */
	int32 OwnerUniqueId;
};

/**
 * Represents map composed from tiles. 
 * This needs to be duplicated as it's not generated by pure actions.
 */
UCLASS()
class UNREALDIPLOMACY_API UUDMapState : public UObject
{
	GENERATED_BODY()
public:
	/**
	 * Creates new instance of the map state.
	 */
	static TObjectPtr<UUDMapState> CreateState(int32 mapSeed, int32 xSizeOfMap, int32 ySizeOfMap);
	/**
	 * Creates new instance of the map state based on existing one.
	 * Used for copying map to a state.
	 */
	static TObjectPtr<UUDMapState>&& Duplicate(TObjectPtr<UUDMapState> existingState);
	/**
	 * Each tile present in the world.
	 */
	TArray<TArray<TObjectPtr<UUDTileState>>> Tiles;
	/**
	 * Seed used by generator.
	 */
	int32 MapSeed = 0;
	/**
	 * X size of Map (first in array).
	 */
	int32 MapSizeOfX = 0;
	/**
	 * Y size of Map (second in array).
	 */
	int32 MapSizeOfY = 0;
};

/**
 * Represents single Player/Ai state.
 */
UCLASS()
class UNREALDIPLOMACY_API UUDNationState : public UObject
{
	GENERATED_BODY()
public:
	/**
	 * Creates new instance of the player state for specified player.
	 */
	static TObjectPtr<UUDNationState> CreateState(int32 playerId);
	/**
	 * Unique id assigned to the owner.
	 */
	int32 PlayerUniqueId;
	/**
	 *
	 */
	int32 ResourceGold = 0;
	/**
	 * List of unresolved requests created by actions 
	 * that are pending for confirm/reject action from this player.
	 */
	TArray<FUDActionData> PendingRequests;
};

/**
 * Holds the state of a world.
 */
UCLASS()
class UNREALDIPLOMACY_API UUDWorldState : public UObject
{
	GENERATED_BODY()
public:
	/**
	 * Creates new instance of the world state.
	 * IsPlayerPerspectiveOnly defines if this state is supposed to hold all knowledge about the world.
	 */
	static TObjectPtr<UUDWorldState> CreateState(int32 playerId, bool isPlayerPerspectiveOnly);

	/**
	 * Id associated with a Player/Ai, that controls this simulation.
	 */
	int32 PerspectivePlayerId;
	/**
	 * State either belongs to specific Player/Ai or is global.
	 */
	bool IsPlayerPerspectiveOnly;
	/**
	 * List of players in turn order, represented only by their unique id.
	 */
	TArray<int32> PlayerOrder;
	/**
	 * Map of players with key as their id.
	 */
	TMap<int32, TObjectPtr<UUDNationState>> Players;
	/**
	 * Current Player/Ai/Server that is able to act.
	 * Default value is 0.
	 */
	int32 CurrentTurnPlayerId = 0;
	/**
	 * Current turn, has no purpose other than flavor info.
	 * Default value is 0.
	 */
	int32 CurrentTurn = 0;
	/**
	 * Gaia id.
	 */
	static const int32 GaiaWorldStateId = 0;
};
