// Copyright Miroslav Valach

#pragma once

#include "CoreMinimal.h"
#include "Core/Simulation/Actions/UDSystemAction.h"
#include "UDSystemActionWorldCreate.generated.h"

/**
 * Duplicates and assigns new World generated by WorldGenerator to all existing states.
 */
UCLASS(Blueprintable, BlueprintType)
class UNREALDIPLOMACY_API UUDSystemActionWorldCreate : public UUDSystemAction
{
	GENERATED_BODY()
public:
	virtual void Execute(const FUDActionData& action, TObjectPtr<UUDWorldState> world) override;
	virtual void Revert(const FUDActionData& action, TObjectPtr<UUDWorldState> world) override;
	virtual int32 GetId() const override { return ActionTypeId; };
	virtual void SetWorldGenerator(TObjectPtr<UUDWorldGenerator> worldGenerator) override;
public:
	static const int32 ActionTypeId = 9;
protected:
	UPROPERTY()
	TWeakObjectPtr<UUDWorldGenerator> WorldGenerator = nullptr;
};